### ISSUE TITLE
Issue new release as 1.0.1 (for go modules)

### ISSUE THREAD

**Issue by gabriel** [tyler-smith/go-bip39#30]
By default,  go modules is picking up the latest release ([1.0.0 tag](https://github.com/tyler-smith/go-bip39/releases/tag/v1.0.0)) which is older. Would it be possible to do a 1.0.1 release, so go mod picks up the latest?

Alternatively go module users will need to `go get github.com/tyler-smith/go-bip39@master`.

Thanks!

**Comment by tyler-smith** [comment]
Done!
