### ISSUE TITLE
MnemonicToByteArray does not validate NewMnemonic

### ISSUE THREAD

**Issue by ThePiachu** [tyler-smith/go-bip39#4]
After generating a mnemonic from NewMnemonic and feeding it to MnemonicToByteArray, the result sometimes fails. For example, passing the seed of 00ae885f8a13b01b698bd3f973d1ec9b generates "absent inmate blood before deposit asset plate kidney west ozone kite cushion", which returns an error of `Mnemonic checksum error. Check words are in correct order. (decoded byte 1)`.

**Comment by ThePiachu** [comment]
And here is a bunch more examples:

`00a84c51041d49acca66e6160c1fa999 - absent draw begin amused stand stool civil system bid genius tuna cram
00ca45df1673c76537a2020bfed1dafd - absorb fall jelly coconut detect raw teach doctor armor walk issue winner
0019d5871c7b81fd83d474ef1c1e1dae - abandon solid gift decline retreat yard aunt model upper thought manual fox
00dcb021afb35ffcdd1d032d2056fc86 - absorb tortoise anchor garage curious wrist inner parrot coffee actor sand assault
0062be7bd09a27288b6cf0eb565ec739 - about bicycle page patrol pen nephew color own twice real range inform
00dc705b5efa0adf25b9734226ba60d4 - absorb toe bitter sadness pass hurdle notice common drama cupboard oblige poverty
0017747418d54c6003fa64fade83374b - abandon roof brown coyote feel copy avocado erode width village soccer notable
000d44d3ee7c3dfa45e608c65384431b - abandon health crunch table sense wood bleak scissors shock order awkward current
008241c1ef976b0323061affe5bf24b9 - above bamboo idea tennis issue light metal select zoo combine since income
00a6aec77e4d16bea80b50a34991aaba - absent cube range wish sphere gap parent head person erode height inner
0011527b8c6ddecb9d0c20beccdeb58d - abandon melody page boat target grape injury lottery salute group pulp brick
001c938c503c8f5a2bba2248ff621546 - abandon tonight toast parrot similar public puzzle dust employ wild luxury miss
0002f90aaf7a8327698f0031b6317c36 - abandon blind dress galaxy popular neck plate theme coyote ranch gallery honey
00bff43071ed7e07f77b14f615993bac - absent zero army toilet subject advance target glad voyage proud exclude flush
00da143e00ef17fc63b6fb22dcc2c326 - absorb spawn auto achieve vapor wreck mom term carpet toward radio erase
00ffc6764fb32a354cab1a3ddefb015d - abstract wreck outside panda crawl boy crawl globe differ water scare rival
0062ef47e0985e8953f24760b7598cdd - about blast spin scorpion magnet dwarf exist employ gaze river glimpse river
003bf9765064f71d304908d906c065f5 - ability thank frown patch exhaust model scorpion canal suit current bonus tunnel
00993851503471439d154b3613947474 - above six begin parrot either peace inmate practice current original brown tribe
007ad0ffe9eae753a483a76af06dfa67 - about story divide stable purpose prefer must insane helmet lock leader soda
00091824db9ec19e663bee51d64c83cc - abandon emotion ankle rescue ugly song ocean lava fade raven can obvious
00f48ac621f7e3cb39b2012ac3121543 - abstract picture ranch dumb lawsuit tortoise traffic dizzy client blush luxury mango
0072917415cdca24dfa66c4a92c885b4 - about nest fringe clog syrup bar leader snow enhance north cannon gym
0027ced2b279ea8a91d29364487cdbf4 - ability dinosaur regret gossip pact earn elder fame gold dumb dad trust
00b9c0d37fb10ba272e55842ad812583 - absent sock crumble youth awful spell slide prison dress hire enact alter
004b3d0d2b9285946c687a5350479c8c - able fly drive fire choose sketch random aunt fashion lion transfer border
00c7c12a37d3a7f8c1532b17c89b724c - absorb dignity enhance hurry denial wise aim grace blind dynamic symptom occur
00f400c5545f06ae17ad00f3041e4e26 - abstract parade course post vacant finish gadget parade vessel can near evidence
001e290be10df4d209f247ac5878662b - abandon vanish drill search tent harbor chief employ proof sense book filter
00bf0f74568e582a7dd1ee64f792ec8b - absent wear tackle public tortoise benefit warrior differ gossip route robot blast
00d2e43ecde6b72b847db1539ed89e23 - absorb now autumn orange hidden noise ball renew fatal walnut chest egg
00cecba6678505bb7bfec8ed307251f6 - absorb iron trumpet someone expect tank useful suit unfold logic nerve universe
000aeed1a9edcbb4bc88f610d3ce84eb - abandon first refuse fatigue syrup surge vendor burst awkward oyster patrol stool
00d06206aadfc25c2b21805d283f15ae - absorb loan like fiber wire come prosper copy frog draft shell fruit
00a31789a2ab2d54f8fadd5331010287 - absent board tiny earn ready price token forum farm marine doll aunt
003493c5f520e8d5c0483e895a121dc9 - ability pig vapor tumble attend helmet abuse amazing matter spatial manual naive
004706112800b76001ece2e268bc830e - able deal lounge exotic arena quote amateur ordinary tiny echo camp brown
00ab31e28bb5305be56e38337dbfa486 - absent flower judge blast fantasy combine noble shove cricket unknown truck asset
006872fe85df6b0fa945248e6f9379d1 - about drum sausage arm wall march pink pig mobile lady taxi peasant
00717e5e375da6934e3cfdf57edaf3bd - about message nurse huge surprise endless decline panic voice walnut rude knee
007f1b46e7b9c4c76e77c434b9bccd6b - about web spider sorry ordinary glove right weasel cruise social crew stomach
00dc93735aa35def3b9a2ff676560205 - absorb tonight system relief cupboard wasp unveil echo wait razor letter arm
002cd5dcd881a49c7b87714c6a570a76 - ability grit jaguar rain bottom evolve unlock until erase famous secret uniform
0013b5af9e13fac87e0c505686cfb6bf - abandon oval hip destroy distance goddess wealth meat final cushion unit left
007ab1ec9526b0bc04b64ae65fd42631 - about stereo kite clean help fun barrel sing town wrong another glance
00abb4e11d8385c1cca905a6a65e9144 - absent frozen debate deposit debate thought crawl camera pluck cream picture marine
00574fc62a0501ad8afada2e246708c3 - able risk various favorite exotic strategy cloud forget comfort case season manage
005207e0a815bb2da6b4c35ec1f2bf52 - able mother wealth expand forum nothing onion observe gain auto quit pistol
00f3460f136fb9700080099cbd62bc18 - abstract olive long chat wine retreat acoustic abuse original twelve pyramid course
007a591f204c03ca7b93981237112526 - about spot elephant dog scan topple unusual indoor banana review enable estate
00cfe0befd428f8e5f83a5bfc801472e - absorb lecture cook whisper cigar shrimp lawn input save divorce fade fragile
00987551ac7a879bf0c09b8bc474d9af - above senior federal flight position social seek beach mesh casual cushion garbage
00cadd3ce3d78e49fbc933a85682df3f - absorb finger execute sibling jump ceiling upset chapter portion reduce result lawn
00bfbf2e346c855ccc360d03281455a1 - absent worth slide hand sign purpose cotton script add doll betray drink
004cdf55d429d028f715544ce22d4f31 - able group step portion other behave sword pride erupt badge fatigue girl
0075c84a7d15e0ac85e1e41025eed23b - about purity barely when fun film bleak develop awake control region jeans
00807dddd61f71725d336cab844d2cb5 - above advance jazz promote warfare rice inquiry horn process carbon enroll hidden
00422f21b77fe20e367467ed98c18410 - able badge silent humble wreck alpha supply mind unique ship genre can
00b44d0ac622907119c626c850a462fd - absent pen dress middle cinnamon decade grow shadow sign lunch board will
00363f5e7f22fc49f3cd662a28956563 - ability rapid stuff wrestle cool ceiling song proud clay dwarf flock sick
000fe5837e68397bbf58db9f221bdc4e - abandon left general wolf logic saddle word bread palace awkward warfare ordinary
0056af33835c888ef0c22599686445d3 - able rely smooth allow silk electric seek dwarf offer drip badge plug
00790a8647fd3dfb38b7e2b6f578f2c6 - about sign pave morning stable work tissue wisdom report profit device mirror
00da8d9009675cb7beec930e263014fb - absorb stamp goat barrel into forward wing mystery athlete cover ahead wasp
00d4b384540a5bb54aa760edaa4fb2fe - absorb pitch three pool pizza survey clever ugly unit fame uncover wool
00be9b1479ed680fdd5d91a41eb926d0 - absent visit shallow video story among install rate piano volume endless parent
009182347502af97077c40a6e74b4b5c - above metal minimum tube cliff slide bulb marine plunge demise spot reunion
00f5c90ee1c67fa77fd821f8e9fab4f1 - abstract purity dry seminar gun squirrel youth aerobic wedding exist pudding together
005568f9a2dd6b0c0cc2f5ba3d9cac38 - able prize dinosaur east stove maid credit gadget riot undo climb ill
008b481f8678577d9cf6aa3f6cd6056b - above fog among artefact lyrics salute inherit stem disorder grit life stone
00c4323ece5e4fe3b6cd4c5c932931af - absorb canoe moral original top vault swamp praise frame off erase garage
009791f7550c3798c5a214cb2d0ea773 - above route lava present sell small bird dream sleep half prefer tree
008a7baab22481f0ad8167dd9f90d55c - above fatigue turkey gold elite weapon render coconut talk wish crystal right
00f0e601519aafdc8ff94975e64c946d - abstract mango leopard permit priority unusual divide circle invest crash celery sweet
0083b61e0daa9219df59d697c270cd31 - above buffalo maple brave powder artefact latin depart oak bean crew glow`

**Comment by ThePiachu** [comment]
Turns out there was an issue with byte array padding. Here is the solution and some unit tests. Feel free to pull the fix to your repo: https://github.com/FactomProject/go-bip39/commit/d1007fb78d9a7ec65314dad412973e63caf4c527

**Comment by tyler-smith** [comment]
Thanks. I will pull in this patch and test as soon as I can.

**Comment by tyler-smith** [comment]
Fixed in lastest verstion.
